services:
    pheat.manager:
        class: %pheat.manager_class%
        arguments:
            - "@pheat.context"

    pheat.context:
        class: %pheat.context_class%

    pheat.provider.session:
        class: %pheat.provider.session_class%

    pheat.provider.config:
        class: %pheat.provider.config_class%

parameters:
    pheat.manager_class: 'Pheat\Manager'
    pheat.context_class: 'Vend\PheatBundle\Pheat\Context'
    pheat.provider.config_class:  'Vend\PheatBundle\Pheat\Provider\ConfigProvider'
    pheat.provider.session_class: 'Vend\PheatBundle\Pheat\Provider\SessionProvider'
